export enum ItemRowMenuElement {
  COMMENTS,
  COPY_NAME_NOT_FAVORITE,
  ADD_ALL_ALARMS,
  WORK_ON_IT,
  ASSIGN_TEAM_MEMBER,
  EDIT_AMOUNT,
  MARK_HQ,
  ADD_TO_ANOTHER_LIST,
  REQUIREMENTS,
  REMOVE_ITEM,
  ADD_TAG,
  MARK_AS_DONE_IN_LOG,
  ATTACH_ROTATION,
  MARKET_BOARD_INFORMATIONS
}
