export enum SearchType {
  ITEM = 'Item',
  RECIPE = 'Recipe',
  ANY = 'Any',
  INSTANCE = 'Instance',
  QUEST = 'Quest',
  NPC = 'NPC',
  LEVE = 'Leve',
  MONSTER = 'Monster',
  LORE = 'Lore',
  FATE = 'Fate',
  MAP = 'Map',
  ACTION = 'Action',
  STATUS = 'Status',
  TRAIT = 'Trait',
  ACHIEVEMENT = 'Achievement',
  FISHING_SPOT = 'Fishing-spot',
  GATHERING_NODE = 'Gathering-node',
}
