export enum NotificationType {
  LIST_COMMENT = 'LIST_COMMENT',
  LIST_ITEM_COMMENT = 'LIST_ITEM_COMMENT',
  DB_ITEM_COMMENT = 'DB_ITEM_COMMENT',
  DB_COMMENT_REPLY = 'DB_COMMENT_REPLY',
  BLOG_POST = 'BLOG_POST',
  COMMISSION = 'COMMISSION'
}
