export enum FiredReason {
  TOO_SLOW = 'TOO_SLOW',
  REFUSING_TO_COMPLETE = 'REFUSING_TO_COMPLETE',
  NO_ACTIVE_SUB = 'NO_ACTIVE_SUB',
  UNCOMFORTABLE_WITH_CONTRACTOR = 'UNCOMFORTABLE_WITH_CONTRACTOR'
}
