export enum FiredReason {
  NO_ACTIVE_SUB = 'NO_ACTIVE_SUB',
  UNCOMFORTABLE_WITH_CONTRACTOR = 'UNCOMFORTABLE_WITH_CONTRACTOR',
  NO_LONGER_NEED_JOB_DONE = 'NO_LONGER_NEED_JOB_DONE',
  FOUND_SOMEONE_ELSE = 'FOUND_SOMEONE_ELSE',
  CANNOT_AFFORD = 'CANNOT_AFFORD'
}
