export enum ResignedReason {
  NO_ACTIVE_SUB = 'NO_ACTIVE_SUB',
  UNCOMFORTABLE_WITH_CLIENT = 'UNCOMFORTABLE_WITH_CLIENT',
  CANNOT_COMPLETE_LEVEL = 'CANNOT_COMPLETE_LEVEL',
  CANNOT_COMPLETE_CONTENT = 'CANNOT_COMPLETE_CONTENT',
  CANNOT_GATHER = 'CANNOT_GATHER'
}
