export const fshLogOrder = [
  'Limsa Lominsa Upper Decks',
  'Limsa Lominsa Upper Decks',
  'Limsa Lominsa Lower Decks',
  'Limsa Lominsa Lower Decks',
  'Middle La Noscea',
  'Zephyr Drift',
  'Rogue River',
  'West Agelyss River',
  'Summerford',
  'Nym River',
  'Woad Whisper Canyon',
  'Lower La Noscea',
  'The Mourning Widow',
  'Moraby Bay',
  'Cedarwood',
  'Oschon\'s Torch',
  'Candlekeep Quay',
  'Moraby Drydocks',
  'Empty Heart',
  'The Salt Strand',
  'Blind Iron Mines',
  'Eastern La Noscea',
  'South Bloodshore',
  'Costa del Sol',
  'North Bloodshore',
  'Rhotano Sea (Privateer Forecastle)',
  'Rhotano Sea (Privateer Sterncastle)',
  'Hidden Falls',
  'East Agelyss River',
  'Raincatcher Gully',
  'The Juggernaut',
  'Red Mantis Falls',
  'North Isle of Endless Summer',
  'Western La Noscea',
  'Swiftperch',
  'Skull Valley',
  'The Brewer\'s Beacon',
  'Halfstone',
  'Isles of Umbra Northshore',
  'The Ship Graveyard',
  'Sapsa Spawning Grounds',
  'Isles of Umbra Southshore',
  'Reaver Hide',
  'Upper La Noscea',
  'Oakwood',
  'Fool Falls',
  'Bronze Lake Shallows',
  'Northeast Bronze Lake',
  'Outer La Noscea',
  'The Long Climb',
  'Northwest Bronze Lake',
  'Mist',
  'Mist',
  'New Gridania',
  'Jadeite Flood',
  'Lower Black Tea Brook',
  'Old Gridania',
  'Whispering Gorge',
  'Upper Black Tea Brook',
  'Central Shroud',
  'The Vein',
  'The Mirror',
  'Everschade',
  'Hopeseed Pond',
  'Haukke Manor',
  'East Shroud',
  'Sweetbloom Pier',
  'Springripple Brook',
  'Sanctum of the Twelve',
  'Verdant Drop',
  'Sylphlands',
  'South Shroud',
  'Upper Hathoeva River',
  'Lower Hathoeva River',
  'East Hathoeva River',
  'Middle Hathoeva River',
  'Goblinblood',
  'Rootslake',
  'Urth\'s Gift',
  'North Shroud',
  'Murmur Rills',
  'Fallgourd Float',
  'Proud Creek',
  'Lake Tahtotl',
  'The Lavender Beds',
  'The Lavender Beds',
  'Western Thanalan',
  'Nophica\'s Wells',
  'The Footfalls',
  'Vesper Bay',
  'Crescent Cove',
  'The Silver Bazaar',
  'Cape Westwind',
  'Moondrip',
  'Parata\'s Peace',
  'Central Thanalan',
  'Upper Soot Creek',
  'Lower Soot Creek',
  'The Clutch',
  'The Unholy Heir',
  'Eastern Thanalan',
  'North Drybone',
  'South Drybone',
  'Yugr\'am River',
  'The Burning Wall',
  'Southern Thanalan',
  'Burnt Lizard Creek',
  'Zahar\'ak',
  'Forgotten Springs',
  'Sagolii Desert',
  'Sagolii Dunes',
  'Northern Thanalan',
  'Bluefog',
  'Ceruleum Field',
  'The Goblet',
  'The Goblet',
  'Coerthas Central Highlands',
  'Coerthas River',
  'Daniffen Pass',
  'The Nail',
  'Dragonhead Latrines',
  'Exploratory Ice Hole',
  'The Weeping Saint',
  'Snowcloak',
  'Sea of Clouds',
  'Witchdrop',
  'Coerthas Western Highlands',
  'Riversmeet',
  'Greytail Falls',
  'Unfrozen Pond',
  'Clearpool',
  'Dragonspit',
  'South Banepool',
  'Ashpool',
  'West Banepool',
  'Mor Dhona',
  'North Silvertear',
  'The Deep Tangle',
  'Singing Shards',
  'Rathefrost',
  'The Tangle',
  'The North Shards',
  'The Sea of Clouds',
  'Voor Sian Siran',
  'The Eddies',
  'Cloudtop',
  'The Blue Window',
  'Mok Oogl Island',
  'Azys Lla',
  'Alpha Quadrant',
  'Aetherochemical Spill',
  'Hyperstellar Downconverter',
  'Delta Quadrant',
  'The Pappus Tree',
  'The Habisphere',
  'The Flagship',
  'The Dravanian Forelands',
  'The Hundred Throes',
  'Whilom River',
  'The Smoldering Wastes',
  'The Iron Feast',
  'Mourn',
  'West Mourn',
  'Anyx Old',
  'Halo',
  'The Dravanian Hinterlands',
  'Thaliak River',
  'Quickspill Delta',
  'Upper Thaliak River',
  'Middle Thaliak River',
  'The Churning Mists',
  'Eil Tohm',
  'Greensward',
  'Weston Waters',
  'Landlord Colony',
  'Sohm Al Summit',
  'Tharl Oom Khash',
  'Rhalgr\'s Reach',
  'Upper Mirage Creek',
  'Rhalgr\'s Reach',
  'The Outer Fist',
  'The Fringes',
  'Timmon Beck',
  'Dimwold',
  'The Comet\'s Tail',
  'The Velodyna River',
  'Mirage Creek',
  'The Peaks',
  'Grymm & Enid',
  'The Slow Wash',
  'Heather Falls',
  'The Ephor',
  'The Bull\'s Bath',
  'The Arms of Meed',
  'The Lochs',
  'Loch Seld',
  'The Ruby Sea',
  'The Ruby Price',
  'Hells\' Lid',
  'The Isle of Bekko',
  'Shoal Rock',
  'Onokoro',
  'Isari',
  'The Isle of Zekki',
  'Yanxia',
  'The Heron\'s Nest',
  'The Heron\'s Way',
  'Namai',
  'The One River (East)',
  'The One River (West)',
  'Plum Spring',
  'Prism Canyon',
  'Prism Lake',
  'Mercantile Docks',
  'Doma Castle',
  'The Azim Steppe',
  'Nem Khaal',
  'Hak Khaal',
  'Upper Yat Khaal',
  'Azim Khaat',
  'Tao Khaal',
  'Lower Yat Khaal',
  'Dotharl Khaa',
  'Kugane',
  'Kugane Piers',
  'Shirogane',
  'Shirogane',
  'The Silver Canal',
  'The Crystarium',
  'The Trivium',
  'The Quadrivium',
  'Crystarium Personal Suites',
  'Eulmore',
  'The Derelicts',
  'Lakeland',
  'The Rift of Sighs',
  'The Rusted Reservoir',
  'The Source',
  'Sullen',
  'The Isle of Ken',
  'Kholusia',
  'Upper Watts River',
  'White Oil Falls',
  'Lower Watts River',
  'Sharptongue Drip',
  'The Western Kholusian Coast',
  'Seagazer Shoals',
  'The Eastern Kholusian Coast',
  'Amh Araeng',
  'The River of Sand',
  'The Nabaath Severance',
  'The Hills of Amber',
  'Il Mheg',
  'Handmirror Lake',
  'Longmirror Lake',
  'The Haughty One',
  'The Jealous One',
  'The Spoiled One',
  'Saint Fathric\'s Temple',
  'Father Collard\'s Failings',
  'The Rak\'tika Greatwood',
  'Lake Tusi Mek\'ta',
  'The Red Chalice',
  'The Lozatl',
  'South Mjrl\'s Regret',
  'Woven Oath',
  'Mjrl\'s Tears',
  'The Tempest',
  'The Flounders\' Floor',
  'Where the Dry Return',
  'Northwest Caliban Gorge',
  'West Caliban Gap',
  'East Caliban Gap',
  'Purpure',
  'The Norvrandt Slope',
  'Old Sharlayan',
  'Scholar\'s Harbor',
  'Oinops',
  'Reflecting Pool',
  'Labyrinthos',
  'Unmoved Source Alpha',
  'The Mover Alpha',
  'Unmoved Source Beta',
  'The Mover Beta',
  'Deepmoat',
  'Radz-at-Han',
  'Meghaduta',
  'Thavnair',
  'Yedlihmad',
  'The Thavnairian Coast',
  'The Great Runoff',
  'Giantsgall Grounds',
  'The Wakeful Torana',
  'Ksiroda',
  'Pavana\'s Remorse',
  'The Font of Maya',
  'The Perfumed Tides',
  'Garlemald',
  'The Eblan Thaw',
  'The Stainless Course',
  'Mare Lamentorum',
  'Greatest Endsvale',
  'The Chlorophospond',
  'The Frozen Fissure',
  'Ultima Thule',
  'Apohelos 18-α',
  'Apohelos 18-β',
  'Apohelos 18-γ',
  'The Wellspring of Regret',
  'Elegeia',
  'Limne 18',
  'Limne 3-α',
  'Limne 3-β',
  'Elpis',
  'Rumination\'s Ramble',
  'The Lower Hungering Gardens',
  'Lethe',
  'Galadion Bay',
  'Outer Galadion Bay',
  'Galadion Spectral Current',
  'The Southern Strait of Merlthor',
  'The Southern Strait of Merlthor',
  'Southern Merlthor Spectral Current',
  'The Northern Strait of Merlthor',
  'The Northern Strait of Merlthor',
  'Northern Merlthor Spectral Current',
  'Rhotano Sea',
  'Open Rhotano Sea',
  'Rhotano Spectral Current',
  'The Cieldalaes',
  'Cieldalaes Margin',
  'Cieldalaes Spectral Current',
  'The Bloodbrine Sea',
  'Open Bloodbrine Sea',
  'Bloodbrine Spectral Current',
  'The Rothlyt Sound',
  'Outer Rothlyt Sound',
  'Rothlyt Spectral Current',
  'The Doman Enclave',
  'The Doman Enclave',
  'The Diadem',
  'Diadem Skysprings',
  'Diadem Grotto',
  'Southern Diadem Lake',
  'Secluded Diadem Pond',
  'Northern Diadem Lake',
  'Blustery Cloudtop',
  'Calm Cloudtop',
  'Swirling Cloudtop',
  'Windswept Cloudtop',
  'Windbreaking Cloudtop',
  'Buffeted Cloudtop',
];
