export const fshLogOrder = [
  'Limsa Lominsa Upper Decks',
  'Limsa Lominsa Upper Decks',
  'Limsa Lominsa Lower Decks',
  'Limsa Lominsa Lower Decks',
  'Middle La Noscea',
  'Zephyr Drift',
  'Rogue River',
  'West Agelyss River',
  'Summerford',
  'Nym River',
  'Woad Whisper Canyon',
  'Lower La Noscea',
  'The Mourning Widow',
  'Moraby Bay',
  'Cedarwood',
  'Oschon\'s Torch',
  'Candlekeep Quay',
  'Moraby Drydocks',
  'Empty Heart',
  'The Salt Strand',
  'Blind Iron Mines',
  'Eastern La Noscea',
  'South Bloodshore',
  'Costa Del Sol',
  'North Bloodshore',
  'Rhotano Sea (Privateer Forecastle)',
  'Rhotano Sea (Privateer Sterncastle)',
  'Hidden Falls',
  'East Agelyss River',
  'Raincatcher Gully',
  'The Juggernaut',
  'Red Mantis Falls',
  'North Isle of Endless Summer',
  'Western La Noscea',
  'Swiftperch',
  'Skull Valley',
  'The Brewer\'s Beacon',
  'Halfstone',
  'Isles of Umbra Northshore',
  'The Ship Graveyard',
  'Sapsa Spawning Grounds',
  'Isles of Umbra Southshore',
  'Reaver Hide',
  'Upper La Noscea',
  'Oakwood',
  'Fool Falls',
  'Bronze Lake Shallows',
  'Northeast Bronze Lake',
  'Outer La Noscea',
  'The Long Climb',
  'Northwest Bronze Lake',
  'Mist',
  'Mist',
  'New Gridania',
  'Jadeite Flood',
  'Lower Black Tea Brook',
  'Old Gridania',
  'Whispering Gorge',
  'Upper Black Tea Brook',
  'Central Shroud',
  'The Vein',
  'The Mirror',
  'Everschade',
  'Hopeseed Pond',
  'Haukke Manor',
  'East Shroud',
  'Sweetbloom Pier',
  'Springripple Brook',
  'Sanctum of the Twelve',
  'Verdant Drop',
  'Sylphlands',
  'South Shroud',
  'Upper Hathoeva River',
  'Lower Hathoeva River',
  'East Hathoeva River',
  'Middle Hathoeva River',
  'Goblinblood',
  'Rootslake',
  'Urth\'s Gift',
  'North Shroud',
  'Murmur Rills',
  'Fallgourd Float',
  'Proud Creek',
  'Lake Tahtotl',
  'The Lavender Beds',
  'The Lavender Beds',
  'Western Thanalan',
  'Nophica\'s Wells',
  'The Footfalls',
  'Vesper Bay',
  'Crescent Cove',
  'The Silver Bazaar',
  'Cape Westwind',
  'Moondrip',
  'Parata\'s Peace',
  'Central Thanalan',
  'Upper Soot Creek',
  'Lower Soot Creek',
  'The Clutch',
  'The Unholy Heir',
  'Eastern Thanalan',
  'North Drybone',
  'South Drybone',
  'Yugr\'am River',
  'The Burning Wall',
  'Southern Thanalan',
  'Burnt Lizard Creek',
  'Zahar\'ak',
  'Forgotten Springs',
  'Sagolii Desert',
  'Sagolii Dunes',
  'Northern Thanalan',
  'Bluefog',
  'Ceruleum Field',
  'The Goblet',
  'The Goblet',
  'Coerthas Central Highlands',
  'Coerthas River',
  'Daniffen Pass',
  'The Nail',
  'Dragonhead Latrines',
  'Exploratory Ice Hole',
  'The Weeping Saint',
  'Snowcloak',
  'Sea of Clouds',
  'Witchdrop',
  'Coerthas Western Highlands',
  'Riversmeet',
  'Greytail Falls',
  'Unfrozen Pond',
  'Clearpool',
  'Dragonspit',
  'South Banepool',
  'Ashpool',
  'West Banepool',
  'Mor Dhona',
  'North Silvertear',
  'The Deep Tangle',
  'Singing Shards',
  'Rathefrost',
  'The Tangle',
  'The North Shards',
  'The Sea of Clouds',
  'Voor Sian Siran',
  'The Eddies',
  'Cloudtop',
  'The Blue Window',
  'Mok Oogl Island',
  'Azys Lla',
  'Alpha Quadrant',
  'Aetherochemical Spill',
  'Hyperstellar Downconverter',
  'Delta Quadrant',
  'The Pappus Tree',
  'The Habisphere',
  'The Flagship',
  'The Dravanian Forelands',
  'The Hundred Throes',
  'Whilom River',
  'The Smoldering Wastes',
  'The Iron Feast',
  'Mourn',
  'West Mourn',
  'Anyx Old',
  'Halo',
  'The Dravanian Hinterlands',
  'Thaliak River',
  'Quickspill Delta',
  'Upper Thaliak River',
  'Middle Thaliak River',
  'The Churning Mists',
  'Eil Tohm',
  'Greensward',
  'Weston Waters',
  'Landlord Colony',
  'Sohm Al Summit',
  'Tharl Oom Khash',
  'Rhalgr\'s Reach',
  'Upper Mirage Creek',
  'Rhalgr\'s Reach',
  'The Outer Fist',
  'The Fringes',
  'Timmon Beck',
  'Dimwold',
  'The Comet\'s Tail',
  'The Velodyna River',
  'Mirage Creek',
  'The Peaks',
  'Grymm & Enid',
  'The Slow Wash',
  'Heather Falls',
  'The Ephor',
  'The Bull\'s Bath',
  'The Arms of Meed',
  'The Lochs',
  'Loch Seld',
  'The Ruby Sea',
  'The Ruby Price',
  'Hells\' Lid',
  'The Isle of Bekko',
  'Shoal Rock',
  'Onokoro',
  'Isari',
  'The Isle of Zekki',
  'Yanxia',
  'The Heron\'s Nest',
  'The Heron\'s Way',
  'Namai',
  'The One River (East)',
  'The One River (West)',
  'Plum Spring',
  'Prism Canyon',
  'Prism Lake',
  'Mercantile Docks',
  'Doma Castle',
  'The Azim Steppe',
  'Nem Khaal',
  'Hak Khaal',
  'Upper Yat Khaal',
  'Azim Khaat',
  'Tao Khaal',
  'Lower Yat Khaal',
  'Dotharl Khaa',
  'Kugane',
  'Kugane Piers',
  'Shirogane',
  'The Silver Canal'
];
